### ISSUE TITLE
Creating widevine encryption dash is not possible

### ISSUE THREAD

**Issue by pavanpalli** [bitmovin/bitcodin-python#1]
When i try to execute create_job_widevine_drm.py then I am facing below issue

Traceback (most recent call last):
  File "create_job_widevine_drm.py", line 42, in <module>
    job_result = bitcodin.create_job(job)
  File "/home/pavan/Downloads/pavan_widevine/bitcodin-python/bitcodin/api.py", line 140, in create_job
    res = RestClient.post(url=get_api_base()+'/job/create', headers=create_headers(), content=job.to_json())
  File "/home/pavan/Downloads/pavan_widevine/bitcodin-python/bitcodin/rest.py", line 59, in post
    RestClient._raise_error(result)
  File "/home/pavan/Downloads/pavan_widevine/bitcodin-python/bitcodin/rest.py", line 43, in _raise_error
    raise BitcodinBadRequestError('The API received a invalid request.', json_result)
bitcodin.exceptions.BitcodinBadRequestError'

Request you to help to resolve the issue

**Comment by dominic-miglar** [comment]
Hello pavanpalli!

I've tested it with various Python versions - 2.6.9 2.7.3, 2.7.10 and 3.4.3. For me it just works fine. 

Could you please tell me the way you installed the bitcodin-python package?

**Comment by pavanpalli** [comment]
Hi,

I took a copy from git via git clone https://github.com/bitmovin/bitcodin-python.git
Python version is 2.6.9, I have attached my script, let me know if there is any issue with script

Kind Regards,
Pavan
Mobile: +91 997 264 4002
[signature-1]

**Comment by dominic-miglar** [comment]
I have not received any attachment, please could you upload the script anywhere and send me a link to it?

**Comment by pavanpalli** [comment]
http://we.tl/qCA16dtdM8

Kind Regards,
Pavan
Mobile: +91 997 264 4002
[signature-1]

**Comment by dominic-miglar** [comment]
With Python 2.6.9 you get not so much information about an Exception when it was thrown. 

With Python 2.7.* i get the following information: 

bitcodin.exceptions.BitcodinBadRequestError: ('The API received a invalid request.', {'status': 400, 'message': 'You have reached your Plan Limits for this period!'})

Thus, you get a bad request because you have reached your Plan Limits for this Billing Period.
