### ISSUE TITLE
Remove testtools from install_requires

### ISSUE THREAD

**Issue by jaap3** [bitmovin/bitcodin-python#3]
Testtools is only used in the test suite, normal users of the library don't really need to install that package at all. Is it OK to remove it from setup.py?

**Comment by moser4035** [comment]
Removed it in verion [1.4.8](https://github.com/bitmovin/bitcodin-python/tree/v1.4.8). Thanks for contribution :+1:

**Comment by jaap3** [comment]
Thanks for the quick follow up and release :)
